### ISSUE TITLE
[Mobile apps] Account and study specific issue > Activities will be in resume status for the below mentioned mobile user

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5018] opened 2022-09-28 08:19 UTC
Steps: 
1. Sign in with the below mentioned credentials
2. Click on the below mentioned enrolled study
3. Submit the responses for the activities
4. Signout from the app
5. Again sign in to the app
6. Click on the study and observe

AR: Activities will be in resume status for the below mentioned mobile user and study
AR: Activities should be completed successfully

User email:
Email: lathan+1328@b..........com

Study name: Copy of New study for the MobileApp [30-08]

**Comment by akashkumarv3** [comment] 2022-10-03 16:18
Hi Latha, Issue is not reproducible.

**Comment by nishit-v** [comment] 2022-10-04 10:32
Since it's account and study specific, issue will be kept under observation.

**Comment by nishit-v** [comment] 2022-10-14 13:29
Issue is not reproducible for any of the user accounts in QA instance. Hence closing this ticket and will re-open if found the scenario or for other users.

**Closed by nishit-v** 2022-10-14 13:29 UTC
Labels: Bug, iOS, Android, P3, Process: under observation
