### ISSUE TITLE
[SB] Landing screen UI adjustment

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3050] opened 2021-01-28 05:15 UTC
SB landing/login   screen - reduce empty space at the top, move all elements (except footer)   upwards to make it appear more centered to the screen
On the same screen, reduce vertical gap   between Study Builder and Welcome, username. Also, footer to be horizontally   centred to the screen.

**Comment by Madhud5** [comment] 2021-01-29 12:26
Hi @SR-btc  and @Lathan-btc i have fixed please check this issue in QA env.
thank you

**Comment by Lathan-btc** [comment] 2021-01-29 17:22
Issue is reproducible in the latest QA instance.

**Comment by Madhud5** [comment] 2021-02-01 06:19
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment] 2021-02-01 08:15
The issue is fixed in the latest Dev instance.

**Closed** 2021-02-01 08:15 UTC
Labels: Bug, P2, Process: Fixed, Process: Tested dev, Study builder, UI
