### ISSUE TITLE
[SB] [Manage apps] Notifications tab is getting displayed on the main bar

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4159] opened 2021-09-28 10:49 UTC
Steps:
1. Login to SB
2. Create an admin by providing permission only for the studies
3. Create an account for the new admin and login to SB
4. Click on Configure studies and observe 

AR: Notifications tab is getting displayed on the main bar
ER: Notifications tab should be hidden when admin doesn't have permission to Manage apps

![image](https://user-images.githubusercontent.com/71445210/135073178-b2b6a174-6176-48ec-b98a-06a66823cb97.png)

**Comment by Lathan-btc** [comment] 2021-09-29 07:01
The issue is fixed in the latest Dev instance.

**Comment by bhoomikav16** [comment] 2021-10-06 05:14
The issue is fixed in the latest QA instance.

**Closed by bhoomikav16** 2021-10-06 05:14 UTC
Labels: Bug, P1, Study builder, Process: Fixed, Process: Tested dev
