### ISSUE TITLE
[Participant Manager] old logo still used in the header

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#2477] opened 2020-12-17 15:54 UTC

**Comment by firdosebtc1** [comment] 2020-12-18 10:31
@Lathan-btc please check this issue as I'm not able to reproduce in both QA and DEV

**Comment by Lathan-btc** [comment] 2020-12-18 12:07
@firdosebtc1 issue is resolved in both QA and Dev intances.

**Closed** 2020-12-18 12:11 UTC
Labels: Bug, P1, Participant manager, Process: Tested QA, Process: Tested dev, UI
