### ISSUE TITLE
[Study Builder] Browser back button generally does not operate as expected (goes back one page but then immediately snaps forward to the page you were already on)

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#1049] opened 2020-09-28 14:14 UTC
Steps:
1. Login into Study builder
2. Navigate to any of the sections
3. Click on browser back button and observe

Actual: Clicking on browser back button goes back one page but then immediately snaps forward to the page you were already on

Expected: Clicking on browser back button should just refresh the page itself

**Comment by Madhud5** [comment] 2022-03-15 05:00
![image](https://user-images.githubusercontent.com/59555917/158309546-d9726014-9f19-49b1-8451-e426c3cfbcf7.png)


Hi @Lathan-btc we not able to disable browser back button, its third party.

**Comment by Madhud5** [comment] 2022-04-14 11:11
Hi @Lathan-btc please check ticket.

Note: The issue is fixed in Firefox and edge browser as per required. but chrome browser its 90% fixed, once page loads user has to do single click on window screen anywhere then application will be work as per required.

**Comment by madhurya-btc** [comment] 2022-04-21 06:53
@Lathan-btc Please test and confirm in the QA instance

**Comment by Lathan-btc** [comment] 2022-04-21 11:15
@Madhud5 
Edge browser:
1. Add notification: if the admin clicks on back button then admin is navigating to the Notification list screen
2. Add admin : if the admin clicks on back button then the admin is navigating to the Manage admin screen

[Note: Issue should be fixed in all the screens where ever issue is present]

**Closed** 2022-04-25 17:01 UTC
Labels: Bug, P1, Study builder, UX, Process: Reopened

**Comment by Madhud5** [comment] 2022-04-26 10:34
Hi @Lathan-btc please check ticket.

Note: The issue is almost fixed in Firefox and edge browser as per required. but chrome browser its 90% fixed, once page loads user has to do single click on window screen anywhere then application will be work as per required.

**Comment by Lathan-btc** [comment] 2022-04-27 06:02
Issue is fixed as per the above comment
