### ISSUE TITLE
[Android] Failure message should be changed , which comes when participants are not eligible for the study in the standalone app

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4582] opened 2022-04-28 13:59 UTC
**Steps:**
1. Install the standalone app
2. Sign up
3. Click on Participate button
4. Fail the eligibility process 
5. Now, Verify the failure message

**AR:** Getting message as attached in the below screenshot

![Android1](https://user-images.githubusercontent.com/86007179/165768472-a815c29b-21de-4593-82e7-94243ac9928e.png)

**ER:** Failure message should be changed , which comes when participants are not eligible for the study in the standalone app

**Comment by bhoomikav16** [comment] 2022-04-29 10:48
Issue is fixed in the latest dev build 1.0(166)

**Comment by Lathan-btc** [comment] 2022-04-29 13:25
The issue is fixed in the latest Dev build 3.0(48)

**Comment by nishit-v** [comment] 2022-10-12 15:05
Issue is fixed in latest QA iOS build V3.0.185

**Comment by Lathan-btc** [comment] 2022-10-13 06:16
Issue is still reproducible in the latest QA iOS build V3.0.187

**Comment by bhoomikav16** [comment] 2022-10-13 06:21
Issue is fixed in the latest QA build 1.0(218)

**Closed** 2022-10-13 06:22 UTC
Labels: Bug, P1, iOS, Android, Process: Fixed, Process: Tested QA, Process: Tested dev
