### ISSUE TITLE
Start time cannot be specified for activity with custom schedule

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#562] opened 2020-06-24 17:37 UTC
When using the 'Custom Schedule' feature for an activity, start and end dates are configurable, but only one time can be configured. It is unclear whether this time is applied to the start time, the end time or both. The desired user experience is to be able to set both a start date + time and an end date + time. Screenshot attached.

![Screenshot 2020-06-24 at 1 33 12 PM](https://user-images.githubusercontent.com/35972680/85605011-d27efb00-b61f-11ea-8f26-edfe8d6c8d22.png)

**Comment by madhurya-btc** [comment] 2020-12-22 08:37
@Madhud5 These changes are related to UI, please fix.

**Comment by Madhud5** [comment] 2021-01-28 05:33
HI @nishit-v i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment] 2021-01-28 13:44
@Madhud5 
1. Questionnaires/Active tasks > Anchor date based > Custom frequency >'Select a time' text is not displaying 

![time1](https://user-images.githubusercontent.com/71445210/106146666-f3529480-619c-11eb-8658-c5e36a859666.png)

2. Active tasks > Regular schedule type > Alignment issue

![time2](https://user-images.githubusercontent.com/71445210/106146728-0b2a1880-619d-11eb-8077-2fabf71043af.png)

**Comment by navya-BTC** [comment] 2021-01-29 10:29
@Lathan-btc test this in QA

**Comment by Lathan-btc** [comment] 2021-01-29 12:25
Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment] 2021-02-01 07:00
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment] 2021-02-01 14:43
Issue is not fixed.

**Comment by SR-btc** [comment] 2021-02-09 08:17
Since adding the separate label is causing functionality issues as reported by the dev team, using this workaround for now:
Revise existing field name to - Select a date range and a start and end time for each run of the activity *

**Comment by Madhud5** [comment] 2021-02-10 11:54
HI @Lathan-btc  I have fixed it please check-in QA env and confirms here.

**Comment by Lathan-btc** [comment] 2021-02-10 13:46
@Madhud5 'Select a date range and a start and end time for each run of the activity *' label is removing when the user clicks on Save/Done button again navigates to edit questionnaire/Active task page

![text11](https://user-images.githubusercontent.com/71445210/107517957-724fc000-6bd4-11eb-8bc5-b4778a293bfe.png)

**Comment by Madhud5** [comment] 2021-02-16 10:30
Hi, @harisboston Please look into this. 
issue raising when the user visiting the same page after add a question.

**Comment by harisboston** [comment] 2021-02-23 12:13
@Lathan-btc Fix is deployed in Dev environment, kindly test and update this ticket.

**Comment by nishit-v** [comment] 2021-02-23 13:31
Issue is resolved in Dev instance.

**Comment by harisboston** [comment] 2021-02-25 08:16
@nishit-v @Lathan-btc Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment] 2021-03-01 11:00
@Madhud5  and @harisboston issue is reproducible in the latest QA instance
AR : Old text is displayed ( Text : Select a time range)
ER : 'Select a date range and a start and end time for each run of the activity *' text should be displayed 


![cust1](https://user-images.githubusercontent.com/71445210/109475237-76685280-7a9b-11eb-981a-f6d5a075073a.png)

**Comment by harisboston** [comment] 2021-03-02 12:01
@Lathan-btc Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment] 2021-03-02 14:37
Issue is fixed in the latest QA instance.

**Closed** 2021-03-02 14:38 UTC
Labels: Feature request, P2, Process: Fixed, Process: Release 2, Process: Tested QA, Process: Tested dev, Study builder, UX
