### ISSUE TITLE
[iOS] [Offline indicator] Activities screen is continuously loading in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4836] opened 2022-08-18 15:42 UTC
Steps:
1. Sign up or sign in to the mobile app
2. Enroll to the study
3. In SB, update the consent for enrolled users
4. In the mobile app, Click on the enrolled study
5. Turn OFF the internet
6. Click on Review and turn ON the internet
7. Click on refresh the page
8. Repeat the step 5 and step 6
9. Observe

AR: Activities screen is loading continuously
ER: Activities should get loaded and displayed to the participants

![image](https://user-images.githubusercontent.com/71445210/185437136-8c0f0c51-3834-4a04-b354-e19370e1908a.png)

**Comment by amruthbtc** [comment] 2022-08-24 10:53
@Lathan-btc issue cannot reproduce, tried multiple times. Please retest in 3.0 (142)

**Comment by Lathan-btc** [comment] 2022-08-25 05:47
@amruthbtc Issue is reproducible in the latest build



https://user-images.githubusercontent.com/71445210/186584571-f76fd8eb-ca7e-4113-8d43-eb0937ec1c58.MOV

**Comment by Lathan-btc** [comment] 2022-08-25 10:26
Issue is fixed in the latest iOS dev build 3.0 (143)

**Comment by nishit-v** [comment] 2022-10-12 13:09
Issue is fixed in latest QA iOS build V3.0.185

**Closed by nishit-v** 2022-10-12 13:09 UTC
Labels: Bug, P0, iOS, Process: Fixed, Process: Tested dev
