### ISSUE TITLE
[PM] Generic/Neutral error logo should be displayed in the static error message pages instead of triangle emoticon logo

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2304] opened 2020-12-09 11:52 UTC
Current screens:
![Screenshot_8](https://user-images.githubusercontent.com/60386291/101626406-f48bfe80-3a42-11eb-9d0f-3f942ed6e1dc.png)

**Comment by Lathan-btc** [comment] 2020-12-24 16:32
@Madhud5 triangle emoticon logo is displayed in the following screen

![icon](https://user-images.githubusercontent.com/71445210/103099257-c1955d80-4633-11eb-9118-d06d07114422.png)

**Comment by Madhud5** [comment] 2021-01-08 05:19
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment] 2021-01-08 10:37
@Madhud5 Issue is still reproducible in both QA and Dev instances.

**Comment by Lathan-btc** [comment] 2021-01-08 12:18
@Madhud5 

1. Gap between icon and text should be reduced
2. Thickness should be text should be same as invision screen in all the error pages

![error1](https://user-images.githubusercontent.com/71445210/104014823-ad2b9600-51d9-11eb-9439-2bfdf509e9d6.png)

**Comment by jkrogers18** [comment] 2021-01-08 13:37
1. Please have the tech writer revise the text.
2. Look into line breaks / wrapping to make the visual layout more balanced

**Comment by Madhud5** [comment] 2021-01-11 11:31
Hi @firdosebtc1  please look into this text revise .

**Comment by firdosebtc1** [comment] 2021-01-15 11:01
@Lathan-btc please check this issue in QA

**Comment by Madhud5** [comment] 2021-01-15 11:21
Hi @Lathan-btc i have fixed please check this in QA - PM

**Comment by Lathan-btc** [comment] 2021-01-15 12:27
@firdosebtc1 Issue is fixed for PM web app.

@monica-BTC This should also be fixed for the Study builder web app.

**Comment by monica-BTC** [comment] 2021-01-16 05:03
@Lathan-btc , please test and confirm

**Comment by Lathan-btc** [comment] 2021-01-18 05:29
The issue is fixed in the latest Dev instance.

**Closed** 2021-01-18 05:30 UTC
Labels: Feature request, P2, Participant manager, Process: Fixed, Process: Release 2, Process: Tested dev, Study builder
