### ISSUE TITLE
Response datastore "could not save response for participant"

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2339] opened 2020-12-11 12:33 UTC
```
Hibernate: select participan0_.id as id1_1_, participan0_.created_time as created_2_1_, participan0_.created_by as created_3_1_, participan0_.participant_id as particip4_1_, participan0_.study_id as study_id5_1_, participan0_.token_id as token_id6_1_ from participant_info participan0_ where participan0_.token_id=? and participan0_.participant_id=?
2020-12-11 12:04:50.801 ERROR 1 --- [nio-8080-exec-9] .h.f.c.ProcessActivityResponseController : Could not save response for participant.
 Study Id: studyid
 Activity Id: testtitle
 Activity Version: 1.0
```

Application.properties has `response.storage.type=`  and the environment has `FILE_STORAGE_PATH=`. Everything else is configured for Cloud Firestore.  When updating the application.properties file to `response.storage.type=file` the issue continues to persist.

Looking into the `participant_info` table of the response datastore's database, I see that the participant ID is is there:
```
+----------------------------------+---------------------+------------+--------------------------------------+----------+---------------------------------------
---------------------------+
| id                               | created_time        | created_by | participant_id                       | study_id | token_id                              
                           |
+----------------------------------+---------------------+------------+--------------------------------------+----------+---------------------------------------
---------------------------+
| 2c918082764f5675017651a925a70000 | 2020-12-11 11:56:48 |            | 9665c596-1a2a-4cb9-832f-3d204152645c | studyid  | f504d413975f30cdbbcaf3af7348a1f54fe677
339658624b8e9361985380058e |
```

But when I look at the likely [origin of the error](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/c6125e8e87101360418a1917c25261fc33151e29/response-datastore/response-server-service/src/main/java/com/google/cloud/healthcare/fdamystudies/dao/ParticipantDaoImpl.java#L102) I don't see why this would be failing.

**Comment by jkrogers18** [comment] 2021-01-07 23:45
Bumping up to P0 as this issue still exists and occurs based on the current deployment documentation. @dhanyak-btc @aswinijena100 FYI

**Comment by moschetti** [comment] 2021-01-07 23:47
I'm also getting this error on the test deployment.
`"2021-01-07 23:03:36.201 ERROR 1 --- [io-8080-exec-10] .h.f.c.ProcessActivityResponseController : Could not save response for participant.`

Error found in Response datastore logs. The request was coming from Android Studio emulated device. Was able to complete setup and enrollment. When I completed a study the app showed the questionnaire as completed, but I was unable to see any response data in Firestore. When I checked the logs I found the error above.

Unable to see what the actual request being sent was.

Additional issue is that the app shows the questionnaire as completed even though the response wasn't saved, so this data is lost and user is unable to retry the questionnaire.

**Comment by aswinijena100** [comment] 2021-01-08 12:01
@moschetti @jkrogers18 Could u please help us in providing few more details to debug the issue.

Please share the record from participant_study_info table for the participant to investigate the issue. What I suspect is,  this could be due to wrongly updated `withdrawal_timestamp` in participant_study_info table even though user is not withdrawn from the study . This column should be NULL if user exist with status `enrolled`

**Comment by moschetti** [comment] 2021-01-08 17:35
Checked `participant_study_info` and it correctly shows `enrolled` and `NULL`

The token does not match. The token listed in `participant_info` table is actually the hash of the enrollment token converted to all CAPS. I enrolled a new user and converted the token to caps, and when I enrolled the tokens matched. Will file separate issue for that. After doing that though, I still received the same error of `.h.f.c.ProcessActivityResponseController : Could not save response for participant.`

**Comment by moschetti** [comment] 2021-01-08 18:22
Changed log level of Response Datastore from WARN to INFO and re-deployed. Unable to get full stack trace.

```
{"log":"Hibernate: insert into participant_activities (activity_id, activity_run_id, activity_state, activity_version, bookmark, completed_count, created_time, missed_count, participant_id, study_id, total_count, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\n","stream":"stdout","time":"2021-01-08T17:59:00.426687444Z"}
{"log":"2021-01-08 17:59:09.025  INFO 1 --- [nio-8080-exec-7] c.g.c.h.f.f.BaseTokenIntrospectionFilter : validate token for /response-datastore/participant/process-response\n","stream":"stdout","time":"2021-01-08T17:59:09.02670171Z"}
{"log":"Hibernate: select participan0_.id as id1_1_, participan0_.created_time as created_2_1_, participan0_.created_by as created_3_1_, participan0_.participant_id as particip4_1_, participan0_.study_id as study_id5_1_, participan0_.token_id as token_id6_1_ from participant_info participan0_ where participan0_.token_id=? and participan0_.participant_id=?\n","stream":"stdout","time":"2021-01-08T17:59:09.145996397Z"}
{"log":"08-Jan-2021 17:59:09.258 SEVERE [http-nio-8080-exec-7] io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.cleanQueue *~*~*~ Channel ManagedChannelImpl{logId=5, target=logging.googleapis.com:443} was not shutdown properly!!! ~*~*~*\n","stream":"stderr","time":"2021-01-08T17:59:09.275625842Z"}
{"log":"    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.\n","stream":"stderr","time":"2021-01-08T17:59:09.275667853Z"}
{"log":"\u0009java.lang.RuntimeException: ManagedChannel allocation site\n","stream":"stderr","time":"2021-01-08T17:59:09.275675783Z"}
```
... stacktrace of the ManagedChannel exception here (same as #2058) ...
```
{"log":"2021-01-08 17:59:09.996 ERROR 1 --- [nio-8080-exec-7] .h.f.c.ProcessActivityResponseController : Could not save response for participant.\n","stream":"stdout","time":"2021-01-08T17:59:09.999018477Z"}
{"log":" Study Id: study1\n","stream":"stdout","time":"2021-01-08T17:59:09.999056153Z"}
{"log":" Activity Id: test\n","stream":"stdout","time":"2021-01-08T17:59:09.999062226Z"}
{"log":" Activity Version: 1.0\n","stream":"stdout","time":"2021-01-08T17:59:09.999067056Z"}
{"log":"2021-01-08 17:59:10.662  INFO 1 --- [nio-8080-exec-6] c.g.c.h.f.f.BaseTokenIntrospectionFilter : validate token for /response-datastore/participant/get-activity-state\n","stream":"stdout","time":"2021-01-08T17:59:10.663154813Z"}
{"log":"Hibernate: select participan0_.id as id1_0_, participan0_.activity_id as activity2_0_, participan0_.activity_run_id as activity3_0_, participan0_.activity_state as activity4_0_, participan0_.activity_version as activity5_0_, participan0_.bookmark as bookmark6_0_, participan0_.completed_count as complete7_0_, participan0_.created_time as created_8_0_, participan0_.missed_count as missed_c9_0_, participan0_.participant_id as partici10_0_, participan0_.study_id as study_i11_0_, participan0_.total_count as total_c12_0_ from participant_activities participan0_ where participan0_.study_id=? and participan0_.participant_id=?\n","stream":"stdout","time":"2021-01-08T17:59:10.676333153Z"}
{"log":"2021-01-08 17:59:10.684  INFO 1 --- [nio-8080-exec-6] ticipantActivityStateResponseServiceImpl : ActivityResponseProcessorServiceImpl getParticipantActivitiesList() - Ends \n","stream":"stdout","time":"2021-01-08T17:59:10.685123918Z"}
```

**Comment by aswinijena100** [comment] 2021-01-12 10:47
@moschetti I have gone through code and found instead of INFO ,DEBUG had been used . Can u pls change it to DEBUG and redeploy . Please share the logs post redeployment

**Comment by moschetti** [comment] 2021-01-12 17:23
logs from DEBUG gathered and emailed to @aswinijena100

**Comment by aswinijena100** [comment] 2021-01-13 11:38
@moschetti Thanks for sharing the logs. I have gone through the logs and found this issue could be happening due to rest call to enroll datastore failing . Hence request you to reverify the url configured for property `enroll.mgmt.service.url` in Response Datastore application.properties is correct or not. However I have raised PR #2833 with additional logger to investigate this issue. Please deploy response server using `issue-2339-Response-Datastore-additional-debugger` branch and share us the log again. Also pls share Participant Enroll Datastore logs for the same time stamp.

**Comment by moschetti** [comment] 2021-01-13 21:16
the URL is coming from the env var which is set to `http://participant-enroll-datastore:50000/participant-enroll-datastore`. However, I believe it should be `http://participant-enroll-datastore-np:50000/participant-enroll-datastore`. This value is incorrectly set in [Response Datastore's tf-deployment.yaml](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/response-datastore/tf-deployment.yaml#L74). Let me try updating this before rebuilding off the debugger branch.

**Comment by moschetti** [comment] 2021-01-13 22:02
Confirmed the issue was with the address used for enroll service in response datastore's terraform deployment config. Tested and submitted fix.

**Comment by aswinijena100** [comment] 2021-01-18 09:53
@moschetti can we close this issue now ?

**Comment by aswinijena100** [comment] 2021-01-19 16:28
@moschetti @jkrogers18 if this issue resolved, can we close this issue

**Comment by aswinijena100** [comment] 2021-01-25 10:23
@moschetti @jkrogers18 as per the discussion issue got resolved at your end without any code fixes, hence closing this ticket. Please reopen if this issue still reproducible at your end.

**Closed by aswinijena100** 2021-01-25 10:23 UTC
Labels: Deployment, P0, Response datastore
