### ISSUE TITLE
[Consent API] [Android] [IOS] Data Sharing screen shot

### ISSUE THREAD

**Issue by navya-BTC** [GoogleCloudPlatform/fda-mystudies#4499] opened 2022-03-18 12:46 UTC
please add a `dataSharingScreenShot ` as a field and provide a data sharing screen shot details in `ConsentStatusBean  `of  "/updateEligibilityConsentStatus" API.

**Comment by Lathan-btc** [comment] 2022-03-21 06:33
@GovindPrasadBostonTechnologyCorporation Before working on the above enhancement please do the following changes to the Data sharing permission screen
1. Remove the arrow marks present which are present next to the Data sharing options
2.
AR:  A participant is automatically navigating to the next screen after selecting any one of the data-sharing permission 
ER: After selecting the data sharing option, the participant should stay in the data-sharing permission screen and he/she should click on next button to navigate to the next page 

![image](https://user-images.githubusercontent.com/71445210/159214432-e832e109-a7e0-4ed0-9ce7-7d8f9a6f918d.png)

**Comment by Lathan-btc** [comment] 2022-03-28 05:20
The issue will be tested once the #4504 issue is fixed.

**Comment by Lathan-btc** [comment] 2022-03-31 05:19
The issue is fixed in the latest iOS build 3.0(31)

**Comment by bhoomikav16** [comment] 2022-05-04 06:47
The issue will be tested once the https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4504 issue is fixed.

**Comment by Lathan-btc** [comment] 2022-07-21 12:02
Issue is fixed in the latest Dev build in both iOS and Android

**Comment by bhoomikav16** [comment] 2022-10-13 14:40
Functionality is implemented in the QA instance

**Closed** 2022-10-13 14:41 UTC
Labels: Feature request, Process: Fixed, Process: Tested QA, Process: Tested dev
