### ISSUE TITLE
[iOS] [Offline indicator] App is getting crashed in the following scenarios

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4681] opened 2022-07-11 16:18 UTC
The app is getting crashed where ever app is navigating to other screens (for eg. refer to the below scenario)
Steps:
1. Sign in to the app
2. Click on the enrolled study
3. Turn off the data
4. Click on the Activity
5. Turn on the data
6. Enter the passcode
7. observe

AR: App is getting crashed
ER: App should not be crashed and participants should stay on the activities screen

Note:
The issue should be fixed on all the screen
1. When the participant clicks on SIgnou or signout later screen with the above scenarios
2. When participants click on consent with the above scenarios etc.

https://user-images.githubusercontent.com/71445210/178310060-33d7898c-a757-4d89-8a92-ab50ca2e0271.MOV

**Comment by amruthbtc** [comment] 2022-07-22 07:36
Issue fixed in 3.96 build

**Comment by nishit-v** [comment] 2022-07-22 09:54
Issue is fixed in Dev iOS V3.0(96) build.  Verified in different screens.

**Comment by nishit-v** [comment] 2022-08-04 09:16
Issue is again reproducible in below scenario:

1. Sign in to the app
2. Click on any study and click on participate
3. Turn off the data
4. Complete till consent flow
5. In signature screen click on next
6. Observe continuous loading animator 
7. Again switch on the data and observe app crashes

AR: App is getting crashed

ER: App should not be crashed and consent confirmation screen should load once participant enables the internet

**Comment by amruthbtc** [comment] 2022-08-11 10:44
Enrollment flow is not suppose to work in offline, we are not saving the data locally, we are restricting at the entry point itself,  if any crash is happening during the enrolment flow, is because of realm db to server syncing. That need to be taken as a separate ticket.

**Comment by nishit-v** [comment] 2022-08-11 10:51
@amruthbtc Please assign to Harshith and check the flow

**Comment by amruthbtc** [comment] 2022-08-12 05:07
@Lathan-btc @nishit-v There is a flow change in the enrolment flow. Enrollment flow is not suppose to work in offline, we are not saving the data locally, we are restricting the usr at the entry point itself, There is a limitation in controlling the enrolment flow without internet, so we made a flow change when there is no internet, as during the enrolment flow, if we lost internet we have to exit from the enrolment process, if any further actions are proceeded without internet. We need BA Confirmation for this alternative flow.

**Comment by Lathan-btc** [comment] 2022-08-12 11:38
The issue is fixed in the latest iOS dev build as per the discussion and the following error message is getting displayed when the user clicks on the button when the participant is offline

error message: 'You may require internet connection to move forward with this flow. Kindly check the internet and try again later.'

**Comment by amruthbtc** [comment] 2022-08-17 16:19
Issue fixed in Build 3.0 (125).

**Comment by Lathan-btc** [comment] 2022-08-18 08:39
Not able to test due to #4830 and #4831 blocker issues in build 3.0(125)

**Comment by amruthbtc** [comment] 2022-08-18 13:22
Please test the build in 3.0 (131) build

**Comment by Lathan-btc** [comment] 2022-08-18 15:06
Issue is fixed in the latest Build build

**Closed** 2022-10-12 12:32 UTC
Labels: Bug, P0, iOS, Process: Fixed, Process: Tested QA, Process: Tested dev
