### ISSUE TITLE
[Mobile Apps] UI issue in the sign in screen of the mobile apps

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4349] opened 2022-01-05 12:04 UTC
UI issue is observed in the sign in screen of the mobile apps (Refer the screenshot attached)

**Note:** Issue should be fixed for both Android and iOS mobile apps

![6](https://user-images.githubusercontent.com/86007179/148215674-d7a80864-c76d-41ef-8bde-577e659d8ea4.png)

**Comment by Madhud5** [comment] 2022-02-08 04:11
Hi @bhoomikav16, please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment] 2022-02-08 11:07
Issue is fixed in the android mobile app.

**Comment by Lathan-btc** [comment] 2022-02-14 11:02
Issue is fixed in the latest Dev instance

**Comment by harisboston** [comment] 2022-03-30 07:04
@bhoomikav16  issue is fixed in QA environment

**Comment by bhoomikav16** [comment] 2022-03-30 07:41
@harisboston  Issue is reproducing in QA instance
![qa1](https://user-images.githubusercontent.com/86007179/160778111-1f80f22c-176d-4b7b-850b-8d4ad491dbba.png)

**Comment by Lathan-btc** [comment] 2022-04-18 17:15
The issue is fixed in the latest QA instance

**Comment by harisboston** [comment] 2022-04-20 06:12
@Lathan-btc This issue is fixed in QA environment

**Comment by bhoomikav16** [comment] 2022-04-20 07:00
@harisboston 
Copy right text is not center aligned in sign in screen in QA instance

![screenshot](https://user-images.githubusercontent.com/86007179/164169264-741080ac-bb3f-47f2-ade2-3d56754214a4.png)

**Closed** 2022-04-20 07:39 UTC
Labels: Bug, P2, iOS, Android, Process: Fixed, Process: Tested dev, Process: Reopened
