### ISSUE TITLE
[Android] Resources are getting displayed in the mobile app irrespective of scheduled time

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3478] opened 2021-04-20 10:57 UTC
Resources are displaying in the mobile app irrespective of the scheduled time
Eg: 1. New Test Study
      2. Study on Heart disease

[Note: Issue observed only for the newly created studies]

Issue is not observed in iOS

**Comment by naveenr-btc** [comment] 2021-04-20 12:05
The issue is because `audience `value is wrong.

**Comment by monica-BTC** [comment] 2021-04-21 12:02
@Lathan-btc, please test and confirm this issue by adding new resources in dev.

**Comment by nagarjunav1** [comment] 2021-04-21 13:38
Issue is fixed now in latest DEV build

**Comment by aswinijena100** [comment] 2021-04-29 06:23
@Lathan-btc please test in QA and close if fixed

**Comment by monica-BTC** [comment] 2021-04-30 10:25
@Lathan-btc, please test and confirm this issue in QA

**Comment by Lathan-btc** [comment] 2021-04-30 15:22
Issue is fixed in the latest QA instance.

**Closed** 2021-04-30 15:23 UTC
Labels: Android, Bug, P1, Process: Fixed, Process: Tested QA, Process: Tested dev
