### ISSUE TITLE
[PM] Responsive issue > Dashboard > UI issue is observed in the sites and studies screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4469] opened 2022-02-24 15:13 UTC
UI issue is observed in the sites and studies screen.

**ER:** No records found should be center aligned.
![1m](https://user-images.githubusercontent.com/86007179/155551656-f332d4e7-ebbb-43a7-9bb2-1a783672170d.png)

**Comment by Madhud5** [comment] 2022-02-28 11:01
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment] 2022-02-28 12:25
@Madhud5 issue is reproducible in the latest Dev instance

Note:
1. Issue is fixed in Dashboard but it is reproducible on other screens
2. Issue should be fixed in all the screens

![image](https://user-images.githubusercontent.com/71445210/155982403-60d4cae5-51ae-4315-8423-56dedf2a78e9.png)

**Comment by Lathan-btc** [comment] 2022-03-02 14:02
Issue is fixed in the latest De instance

**Comment by Madhud5** [comment] 2022-04-13 12:51
Hi @Lathan-btc please check this issue and let me know.
thank you

**Comment by Lathan-btc** [comment] 2022-04-13 15:29
The issue is fixed in the latest QA instance

**Closed by Lathan-btc** 2022-04-13 15:29 UTC
Labels: Bug, P2, Participant manager, Process: Fixed, Process: Tested dev
