### ISSUE TITLE
[IDP] [PM] Not able to add non-organizational admins in the participant manager

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4866] opened 2022-08-29 05:28 UTC
Not able to add non-organizational admins in the participant manager

**Comment by Madhud5** [comment] 2022-10-27 11:20
@Lathan-btc issue fixed pls check and close this

**Comment by Lathan-btc** [comment] 2022-10-27 11:24
The issue is fixed in the latest IDP branch

**Comment by bhoomikav16** [comment] 2022-11-25 05:30
The issue is fixed in the latest IDP QA branch

**Closed** 2022-11-25 05:30 UTC
Labels: Bug, Blocker, P0, Participant manager, Process: Fixed, Process: Tested QA, Process: Tested dev
