### ISSUE TITLE
[SB] [Copy] App ID is getting retained in caps for the new studies   

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3997] opened 2021-08-06 05:19 UTC
Steps
1. Create a study
2. Enter the app in small letters
3. Complete the sections
4. Copy the particular study 
5. Observe

AR: Data in the app id field is getting retained in the caps for the copied studies  
ER: App id should be retained in the same text case whatever is present in the original study

**Comment by Lathan-btc** [comment] 2021-08-06 15:48
The issue is fixed in the latest Dev instance.

**Comment by bhoomikav16** [comment] 2021-08-13 12:15
The issue is fixed in the latest QA instance

**Closed by bhoomikav16** 2021-08-13 12:15 UTC
Labels: Bug, P2, Study builder, Process: Fixed, Process: Tested dev
