### ISSUE TITLE
[SB][Copy/import last published version] Contents are not getting retained in the new study from the consent section for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3968] opened 2021-07-28 12:16 UTC
**Steps:**
1. Create a new study
2. Add all contents and complete all the section
3. Launch the study
4. Edit the study again and add some content
5. Publish the updates
6. Edit the study again and add some content
6. Let study be in draft
7. Copy the last published version of the study. Successfully copied
7. Edit copied study and observe the contents from the consent section

**AR:** Contents from the consent section to the notifications section are not getting retained in the new study 
**ER:** All the contents should be retained as it is whatever is present in the last published version of the study

**Note:** 
1. Issue observed for both copy and import last published version of the study
2. Issue not observed for copy/import last working version of the study

**Comment by Kantharajut-btc** [comment] 2021-08-02 14:48
@Lathan-btc this issue is fixed in dev, please check and confirm.

**Comment by Lathan-btc** [comment] 2021-08-02 15:42
Issue is fixed in the latest Dev instance.

**Comment by bhoomikav16** [comment] 2021-08-16 06:35
The issue is fixed in the latest QA instance

**Closed by bhoomikav16** 2021-08-16 06:35 UTC
Labels: Bug, P0, Study builder, Process: Fixed, Process: Tested dev
