### ISSUE TITLE
[IDP][PM][MFA Enabled] Admin is not authenticated with 2 factor authentication even though MFA is enabled

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5024] opened 2022-10-03 08:50 UTC
**Pre-condition:** IDP and MFA should be enabled in the PM

**Steps:**
1. Add organizational user in the participant manager
2. Complete set up your account process
3. Sign in with registered credentials and Verify

**AR:** Admin is not authenticated with 2-factor authentication even though MFA is enabled
**ER:** Admin should be authenticated with 2-factor authentication if MFA is enabled

**Comment by harisboston** [comment] 2022-10-10 13:58
Looks like issue is happening because of #4866 , once its fixed from front end, then we need to test from backend as IdP user list is not available in email dropdown.

**Comment by bhoomikav16** [comment] 2022-10-27 11:25
Issue is fixed in the latest IDP dev branch

**Comment by bhoomikav16** [comment] 2022-11-03 08:34
Issue is still reproducing in the latest IDP dev branch

**Comment by Lathan-btc** [comment] 2022-11-03 14:45
Issue is fixed in the latest IDP deployment

**Comment by bhoomikav16** [comment] 2022-11-25 11:31
Issue is fixed in the latest QA instance

**Closed** 2022-11-25 11:31 UTC
Labels: Bug, Blocker, P0, Participant manager, Process: Fixed, Process: Tested QA, Process: Tested dev
