### ISSUE TITLE
[SB] [Manage apps] Add/edit admin screen > Study admin > 'Select and add studies' dropdown > UI issue 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4162] opened 2021-09-29 07:40 UTC
Add/edit admin screen > Study admin > 'Select and add studies' dropdown > Fields are not aligned properly 

![image](https://user-images.githubusercontent.com/71445210/135224292-9d5e9440-bc18-4986-ae4a-5f31275e1079.png)

**Comment by Madhud5** [comment] 2021-09-30 09:36
HI, @Lathan-btc I have fixed in Dev pls check and let me know.
thank you.

**Comment by Lathan-btc** [comment] 2021-09-30 10:52
@Madhud5 issue is reproducible in the latest Dev instance

![image](https://user-images.githubusercontent.com/71445210/135442273-4af43243-8db2-4b5b-b8cf-e2d0433785a1.png)

**Comment by Lathan-btc** [comment] 2021-10-01 11:02
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment] 2021-10-05 11:02
@Lathan-btc  Please test in QA and close if fixed.

**Comment by Lathan-btc** [comment] 2021-10-05 12:30
Issue is fixed in the latest QA instance.

**Comment by bhoomikav16** [comment] 2021-11-18 13:14
UI issue in the add/edit admin screen > Study admin > Select and add studies dropdown.

**AR:**  There is no scroll down icon in the dropdown.
**ER:**  Scroll down icon should be displayed.


![Untitledm](https://user-images.githubusercontent.com/86007179/142421924-ec111ff6-6a08-4f05-8520-6083f5ece078.png)

**Comment by bhoomikav16** [comment] 2021-11-19 15:16
The issue is fixed in the dev instance.

**Closed by bhoomikav16** 2021-11-19 15:16 UTC
Labels: Bug, P2, Study builder, Process: Fixed, Process: Tested QA, Process: Tested dev
