### ISSUE TITLE
[SB] Active task > Custom schedule > Added rows are getting removed when admin clicks on Save button for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3969] opened 2021-07-29 13:02 UTC
**Steps**
1. Edit study
2. Go to the active tasks and click on add active tasks
3. Select a Custom schedule 
4. Add more than one run
5. For any one of the runs, don't enter any data into one of the fields
6. Click on Save and observe

**AR:** Added run as per 5th step is getting removed
**ER:** Rows should be saved with the entered data

**Note:**
1. Issue observed for Active tasks > Regular and anchor date
2. Issue not observed foe the questionnaires 

https://user-images.githubusercontent.com/71445210/127496438-f284660e-e8ad-4709-b1a8-afbe44651c9d.mp4

**Comment by harisboston** [comment] 2021-07-30 14:02
@Lathan-btc empty row is getting removed on save, can you please confirm the steps

**Comment by harisboston** [comment] 2021-08-04 08:13
@Lathan-btc Issue is fixed in dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment] 2021-08-04 11:26
@harisboston Issue is reproducible in te latest Dev instance

**Comment by Lathan-btc** [comment] 2021-08-09 12:13
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment] 2021-08-10 06:21
@Lathan-btc Please test in QA and close if fixed

**Comment by Lathan-btc** [comment] 2021-08-10 07:52
The issue is reproducible in the latest QA instance.

**Comment by harisboston** [comment] 2021-08-10 09:39
@Lathan-btc Issue was reproducible because of deployment issue, please retest and close if fixed.

**Comment by Lathan-btc** [comment] 2021-08-10 11:01
The issue is fixed in the latest QA instance.

**Closed** 2021-08-10 11:02 UTC
Labels: Bug, P1, Study builder, Process: Fixed, Process: Tested QA, Process: Tested dev
