### ISSUE TITLE
[SB] [Manage Apps] Developer configurations > Continuous loading animator on clicking on mark as complete for the following scenario

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4117] opened 2021-09-09 13:50 UTC
Steps:
1. Navigate to Manage apps
2. Create an app and distribute the app(s)
3. Click on the edit button of the app
4. Navigate to Developer configurations
5. Click on Save and Mark as completed button and observe

Actual: iOS/Android Bundle ID and iOS/Android Server Key text fields are blank and clicking on mark as complete, continuous loading animator

Expected: Page should be saved 

Unable to test force upgrade/any other functionalities due to this

**Comment by madhurya-btc** [comment] 2021-09-09 16:12
@nishit-v Please test and confirm in dev instance

**Comment by Lathan-btc** [comment] 2021-09-13 05:46
The issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment] 2021-10-05 11:09
@nishit-v Please test and confirm in QA instance

**Comment by Lathan-btc** [comment] 2021-10-06 07:32
Issue is fixed in the latest QA instance.

**Closed** 2021-10-06 07:33 UTC
Labels: Bug, Blocker, P0, Study builder, Process: Fixed, Process: Tested QA, Process: Tested dev
