### ISSUE TITLE
[Android] Issues with respect to push notifications in the mobile app 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4898] opened 2022-09-05 13:24 UTC
Issues with respect to push notifications in the mobile app,

**Scenario1:**
Add resources with anchor-date based period in the SB with 'Text for notifying participants about the new resource being available' field should not be configured in the resources screen and then Publish the study,
**AR:**  Blank push notifications are getting displayed in the mobile app 
**ER:**  Push notifications should not get displayed in the mobile app

![android](https://user-images.githubusercontent.com/86007179/188459924-b5a445d6-8a2f-4265-bbe6-7f3533476b12.png)

**Scenario2:**
Add resources in the SB with 'Text for notifying participants about the new resource being available' field should be configured in the resources screen and then Publish the study,
**AR:** Old push notifications are getting displayed again for resources when navigated to resources screen
**ER:**  Old push notifications should not get displayed again for resources when navigated to resources screen

**Comment by Shashank-btc** [comment] 2022-09-06 07:50
Hi @bhoomikav16 

Scenario 1:
we need a device because this is device specific issue we con't able to reproduce in own device.

Scenario 2:
This push notification is triggering by the device we don't have any controll over there.

Thanks

**Comment by nagarjunav1** [comment] 2022-09-12 08:24
Issue will be tested once #4897 is fixed

**Comment by Shashank-btc** [comment] 2022-09-14 08:45
Hi,

Local notifications will be triggered dependes on the anchor date, when user navigate to resources screen (StudyLevel). 
When user logs out and and logs in all the notification will trigger again, if there is any anchor data related resources.

Thanks

**Comment by nagarjunav1** [comment] 2022-09-14 09:43
Issue is fixed now in the latest Android build v1.0(206)

**Comment by bhoomikav16** [comment] 2022-10-13 08:09
Issue is fixed in the latest QA build

**Closed** 2022-10-13 08:09 UTC
Labels: Bug, P1, Android, Process: Fixed, Process: Tested QA, Process: Tested dev
