### ISSUE TITLE
[Mobile apps] stats are not displaying for some studies 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3191] opened 2021-02-17 15:38 UTC
Steps
1. Create/Edit study
2. Navigate Questionnaires/Active tasks 
3. Add questionnaire/active task with stats
4. Launch/publish the study
5. Join a study through a mobile app
6. Mobile app > Click on Dashboard and observe

AR : Stats are not displaying
ER : Stats should be displayed

[Note: Stats are not displaying for the following studies
           1. Covid Self Monitoring and precautions
           2. Global Mental Health of Urban Mothers (MUM)]
           
![image](https://user-images.githubusercontent.com/71445210/108226987-6aa79280-7163-11eb-993c-5ee0504217a4.png)

**Comment by Kantharajut-btc** [comment] 2021-03-10 14:15
@Lathan-btc this issue is fixed in dev, please check and confirm

**Comment by Lathan-btc** [comment] 2021-03-12 07:03
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment] 2021-03-19 08:17
@Lathan-btc please test this issue in dev and close if the issue is not reproducing

**Comment by Lathan-btc** [comment] 2021-03-23 13:35
Issue is not reproducible for other studies

**Closed** 2021-03-23 13:34 UTC
Labels: Bug, P2, Process: Fixed, Process: Tested dev, Study builder
