### ISSUE TITLE
[PM] Sign in screen > 'User not found' error message is getting displayed in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4961] opened 2022-09-15 13:33 UTC
Steps:
1. Login to PM as Superadmin
2. Go to the Admins
3. Deactivate the active admin
4. Sign out 
5. Try to sign in with the deactivated admin credential
6. Observe

AR: 'User not found' error message is getting displayed
ER: 'Your account has been deactivated' error message should get displayed in the above scenario

**Comment by Lathan-btc** [comment] 2022-09-21 06:05
Issue observed for deactivated super admins

**Comment by harisboston** [comment] 2022-09-21 07:38
Issue is not replicating for new user deactivated super admins.
Issue is happening only for few users like  'lathan+3@boston-technology.com' ,

In auth server DB I can see two records
email lathan+3@boston-technology.com      app_id = GCPMOB001  created_data= 2022-05-18 12:14:12
email lathan+3@boston-technology.com      app_id = GCPDEV001   created_data=  2022-04-01 21:01:44

There is no record for app_id = Participant Manager, looks this happened because of an old IdP bug, where record was not getting created in auth DB during registration process was getting updated in PMD DB.
So that user is visible in the Participant manager but when that user tries to sign-in, will get a "User not found" error.

**Comment by nishit-v** [comment] 2022-09-21 11:28
Issue is not reproducible for newly deactivated users and hence closing this ticket.

**Closed by nishit-v** 2022-09-21 11:28 UTC
Labels: Bug, P1, Participant manager, Process: Fixed
