### ISSUE TITLE
[SB] Modify text format for inline errors

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3383] opened 2021-03-21 12:10 UTC
For all inline error messages that are short phrases and single sentences, remove the period at the end of the sentence. E.g.
'Please fill out this field'

**Comment by chiranjibi009** [comment] 2021-03-23 12:33
@Lathan-btc Please test the issue in dev environment and update

**Comment by Lathan-btc** [comment] 2021-03-23 14:27
Issue is still reproducible in the latest Dev instance.

**Comment by Madhud5** [comment] 2021-04-19 12:35
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Madhud5** [comment] 2021-04-20 10:39
Hi @latha  i have checked in DEV its fixed. Please check and let me know.

**Comment by Madhud5** [comment] 2021-04-20 10:40
Hi @latha  i have checked in DEV its fixed. Please check and let me know.

**Comment by Madhud5** [comment] 2021-04-20 10:41
Hi @latha  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment] 2021-04-20 12:30
@Madhud5 Issue is reproducible for the following
1. Questionnaires > Question level attributes > line chart and stats
2. Questionnaires > Response level attributes - It should be fixed for all the response types

**Comment by Madhud5** [comment] 2021-04-21 10:46
Hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment] 2021-04-22 07:19
Issue is reproducible in the latest Dev instance.

**Comment by Madhud5** [comment] 2021-04-29 05:21
Hi @Lathan-btc I have fixed in DEV- QA. Please check and close the issue.

**Comment by Lathan-btc** [comment] 2021-04-29 08:50
@Madhud5 Issue is still reproducible in the latest QA instances 

Questionnaires/Active task >Shcedule tab > Other than one-time frequency > it should be fixed for both regular and anchor date

**Comment by Madhud5** [comment] 2021-04-30 10:53
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment] 2021-04-30 12:06
@Madhud5 Issue is reproducible for the following scenario
Questionnaires > Response level attributes - It should be fixed for all the response types - the issue is reproducible for the Form step

**Comment by Madhud5** [comment] 2021-05-03 09:50
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment] 2021-05-03 13:13
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment] 2021-05-06 08:10
Issue is fixed in the latest QA instance.

**Closed by nishit-v** 2021-05-06 08:10 UTC
Labels: Bug, P2, Process: Fixed, Process: Tested dev, Study builder, UX
